name: Unit Test

on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format Code and Check for errors
        run: pnpm run format:check

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Start dev server
        run: pnpm dev &

      - name: Wait for server
        run: npx wait-on http://localhost:3000/admin

      - name: Test
        run: pnpm run test
