name: Unit Test

on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URI: mongodb://127.0.0.1:27017/payload-email-template
      PAYLOAD_SECRET: YOUR_SECRET_HERE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Format Code and Check for errors
        run: pnpm run format:check

      - name: Test
        run: pnpm run test
